### ISSUE TITLE
Feature request: Bundleless approach for using AltList

### ISSUE THREAD

**Issue by PoomSmart** [opa334/AltList#15]
Seen from the example AltList project, there’s still the need to build s bundle that does nothing more than loading the Root plist. Just like AppList, it would be handy if we can plug `bundle` and `isController` properties and everything in one plist. `AltList.bundle` should be created or symlinked to `/System/Library/PreferenceBundles`, to start the matter.

**Comment by opa334** [comment]
I have tried this and while I got it working, unfortunately PreferenceLoader / iOS seems to take the NSPrincipalClass of the preference bundle (https://github.com/opa334/AltList/blob/classless/Resources/Info.plist#L22) as the detail class instead of the class specified in the plist (https://github.com/opa334/AltList/blob/classless/AltListTestClasslessPreferences/layout/Library/PreferenceLoader/Preferences/AltListTestClasslessPreferences.plist#L12).

So the only way to add something like this as far as I can tell would be to make a preference bundle for each class.
